name = "yolopadweb"
compatibility_date = "2025-04-01"

[site]
bucket = "./build"

[build]
command = "npm run build"
output_dir = "build"

[env.production]
routes = [
  { pattern = "/*", dest = "/index.html" }
]

[env.staging]
routes = [
  { pattern = "/*", dest = "/index.html" }
] 